/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author --User31--
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 153, 255));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(480, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel1.setText("Sidenreng Rappang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 370, 150, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/IMG_0094.JPG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 10, 420, 200);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 210, 420, 2);

        jLabel7.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 330, 100, 20);

        jLabel8.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Telepon");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 330, 100, 20);

        jLabel9.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setText("Tanggal Lahir");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 280, 100, 20);

        jLabel2.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel2.setText("082292473676");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 350, 190, 20);

        jLabel3.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel3.setText("January 5th, 1998");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 300, 130, 20);

        jLabel4.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel4.setText("Wette'E, Panca Lautang,");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 350, 150, 20);

        jLabel10.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 204));
        jLabel10.setText("Nama Lengkap");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 230, 100, 20);

        jLabel11.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 204));
        jLabel11.setText("Email");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 230, 100, 20);

        jLabel12.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 204));
        jLabel12.setText("Line");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 280, 100, 20);

        jLabel5.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel5.setText("Suci Ramadhani");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 130, 20);

        jLabel13.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel13.setText("suciramadhanirauf5@gmail.com");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(260, 250, 190, 20);

        jLabel14.setFont(new java.awt.Font("LaurenScript", 0, 12)); // NOI18N
        jLabel14.setText("suciramrauf");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 300, 190, 20);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 240, 0, 50);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 400, 1, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(220, 220, 20, 190);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/putih.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 460, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenUtama().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
