/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author --User31--
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        vusername = new javax.swing.JTextField();
        vpassword = new javax.swing.JPasswordField();
        Blogin = new javax.swing.JButton();
        CBPass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 310));
        setResizable(false);
        getContentPane().setLayout(null);

        vusername.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        vusername.setBorder(null);
        getContentPane().add(vusername);
        vusername.setBounds(100, 110, 230, 20);

        vpassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        vpassword.setBorder(null);
        getContentPane().add(vpassword);
        vpassword.setBounds(100, 150, 230, 20);

        Blogin.setBackground(new java.awt.Color(0, 102, 204));
        Blogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Blogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/login.jpg"))); // NOI18N
        Blogin.setText("LOGIN");
        Blogin.setBorder(null);
        Blogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Blogin.setDisabledIcon(null);
        Blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloginActionPerformed(evt);
            }
        });
        getContentPane().add(Blogin);
        Blogin.setBounds(60, 220, 330, 30);

        CBPass.setBackground(new java.awt.Color(255, 255, 255));
        CBPass.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CBPass.setText("Lihat Password");
        CBPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPassActionPerformed(evt);
            }
        });
        getContentPane().add(CBPass);
        CBPass.setBounds(70, 180, 150, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/simple_login_form1.jpg"))); // NOI18N
        jLabel1.setText("User");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 280);
        getContentPane().add(jOptionPane1);
        jOptionPane1.setBounds(520, 20, 50, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloginActionPerformed
        // TODO add your handling code here:
        if (vusername.getText().equals("suci") &&
            vpassword.getText().equals("12345")) {
            jOptionPane1.showMessageDialog(rootPane,"LOGIN SUKSES !!!");
            new MenUtama().show();
            this.dispose();
        }else{
            jOptionPane1.showMessageDialog(rootPane,"Username atau Password yang anda masukkan salah !");
            vusername.setText("");
            vpassword.setText("");
        }
    }//GEN-LAST:event_BloginActionPerformed

    private void CBPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPassActionPerformed
        // TODO add your handling code here:
        if (CBPass.isSelected() == true){
            vpassword.setEchoChar((char)0);
        }
        else
        {
            vpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_CBPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blogin;
    private javax.swing.JCheckBox CBPass;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField vpassword;
    private javax.swing.JTextField vusername;
    // End of variables declaration//GEN-END:variables
}
