/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author --User31--
 */
public class MenUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenUtama
     */
    public MenUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Transaksi = new javax.swing.JButton();
        Penyewa = new javax.swing.JButton();
        About = new javax.swing.JButton();
        Kamar = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(307, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/transaksi.png"))); // NOI18N
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(Transaksi);
        Transaksi.setBounds(20, 320, 60, 60);

        Penyewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/penyewa.png"))); // NOI18N
        Penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyewaActionPerformed(evt);
            }
        });
        getContentPane().add(Penyewa);
        Penyewa.setBounds(20, 200, 60, 60);

        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1475212058078.png"))); // NOI18N
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        getContentPane().add(About);
        About.setBounds(80, 10, 150, 150);

        Kamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kamar.png"))); // NOI18N
        Kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KamarActionPerformed(evt);
            }
        });
        getContentPane().add(Kamar);
        Kamar.setBounds(20, 260, 60, 60);

        Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.jpg"))); // NOI18N
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });
        getContentPane().add(Report);
        Report.setBounds(20, 380, 60, 60);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/out.png"))); // NOI18N
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(20, 440, 60, 60);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Maximum High Tension", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Penyewa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 220, 60, 20);

        jLabel5.setFont(new java.awt.Font("Maximum High Tension", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kamar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 280, 50, 20);

        jLabel6.setFont(new java.awt.Font("Maximum High Tension", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transaksi");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 340, 80, 30);

        jLabel7.setFont(new java.awt.Font("Maximum High Tension", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Report");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 400, 50, 30);

        jLabel9.setFont(new java.awt.Font("Maximum High Tension", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Logout");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 450, 60, 40);

        jLabel2.setFont(new java.awt.Font("PassingNotes", 0, 18)); // NOI18N
        jLabel2.setText("Suci Ramadhani");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 160, 120, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 190, 300, 10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/putih.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 300, 190);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_181.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 190, 300, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void PenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyewaActionPerformed
        // TODO add your handling code here:
        new Penyewa().show();
        this.dispose();
    }//GEN-LAST:event_PenyewaActionPerformed

    private void KamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KamarActionPerformed
        // TODO add your handling code here:
        new Kamar().show();
        this.dispose();
    }//GEN-LAST:event_KamarActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here:
        new Transaksi().show();
        this.dispose();
    }//GEN-LAST:event_TransaksiActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
        new Report().show();
        this.dispose();
    }//GEN-LAST:event_ReportActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        new About().show();
        this.dispose();
    }//GEN-LAST:event_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton Kamar;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Penyewa;
    private javax.swing.JButton Report;
    private javax.swing.JButton Transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
