import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import com.mysql.jdbc.Statement;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import koneksi.conek;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author --Suci Ramadhani--
 */

public class Penyewa extends javax.swing.JFrame { 
    private DefaultTableModel model;

    /**
     * Creates new form Penyewa
     */
    
    
    
    public Penyewa() {
        initComponents();
        bersih();
        model = new DefaultTableModel();
        tabel.setModel(model);
            model.addColumn("Registrasi");
            model.addColumn("Nama");
            model.addColumn("Gender");
            model.addColumn("Agama");
            model.addColumn("Pekerjaan");
            model.addColumn("Telepon"); 
            
            getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CBRegis = new javax.swing.JComboBox();
        CBPengenal = new javax.swing.JComboBox();
        CBAgama = new javax.swing.JComboBox();
        TNama = new javax.swing.JTextField();
        TAlamat = new javax.swing.JTextField();
        THp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TTtl = new javax.swing.JTextField();
        TPekerjaan = new javax.swing.JTextField();
        TId = new javax.swing.JTextField();
        BEdit = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();
        BClear = new javax.swing.JButton();
        BReport = new javax.swing.JButton();
        BHome = new javax.swing.JButton();
        BSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Tgl = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Penyewa");
        setPreferredSize(new java.awt.Dimension(495, 500));
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Registrasi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TTL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 80, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat Asal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 80, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 100, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Pengenal");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 190, 100, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agama");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 220, 70, 14);

        CBRegis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "17A1", "17A2", "17A3", "17A4", "17A5", "17A6", "17A7", "17A8", "17A9", "17A10", "17B1", "17B2", "17B3", "17B4", "17B5", "17B6", "17B7", "17B8", "17B9", "17B10", "18A1", "18A2", "18A3", "18A4", "18A5", "18A6", "18A7", "18A8", "18A9", "18A10", "18B1", "18B2", "18B3", "18B4", "18B5", "18B6", "18B7", "18B8", "18B9", "18B10" }));
        getContentPane().add(CBRegis);
        CBRegis.setBounds(110, 30, 140, 30);

        CBPengenal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KTP", "SIM", "Kartu Pelajar" }));
        CBPengenal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPengenalActionPerformed(evt);
            }
        });
        getContentPane().add(CBPengenal);
        CBPengenal.setBounds(110, 180, 140, 30);

        CBAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISLAM", "HINDU", "BUDDHA", "KRISTEN PROTESTAN", "KHATOLIK", "KONG HU CHU" }));
        getContentPane().add(CBAgama);
        CBAgama.setBounds(110, 210, 140, 30);
        getContentPane().add(TNama);
        TNama.setBounds(110, 60, 370, 30);
        getContentPane().add(TAlamat);
        TAlamat.setBounds(110, 120, 370, 30);
        getContentPane().add(THp);
        THp.setBounds(330, 210, 150, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pekerjaan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 160, 60, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Pengenal");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 190, 70, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Handphone");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 220, 80, 14);
        getContentPane().add(TTtl);
        TTtl.setBounds(110, 90, 220, 30);
        getContentPane().add(TPekerjaan);
        TPekerjaan.setBounds(330, 150, 150, 30);
        getContentPane().add(TId);
        TId.setBounds(330, 180, 150, 30);

        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/edit.jpg"))); // NOI18N
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit);
        BEdit.setBounds(100, 250, 60, 59);

        BDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/HAPUS.jpg"))); // NOI18N
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BDelete);
        BDelete.setBounds(180, 250, 60, 60);

        BClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete.jpg"))); // NOI18N
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearActionPerformed(evt);
            }
        });
        getContentPane().add(BClear);
        BClear.setBounds(260, 250, 60, 60);

        BReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.jpg"))); // NOI18N
        BReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReportActionPerformed(evt);
            }
        });
        getContentPane().add(BReport);
        BReport.setBounds(340, 250, 60, 60);

        BHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/home.jpg"))); // NOI18N
        BHome.setBorder(null);
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BHome);
        BHome.setBounds(420, 250, 60, 60);

        BSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save.jpg"))); // NOI18N
        BSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSaveActionPerformed(evt);
            }
        });
        getContentPane().add(BSave);
        BSave.setBounds(20, 250, 60, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 320, 460, 10);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 330, 460, 130);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 390, 10, 10);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("L");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(110, 150, 70, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("P");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(180, 150, 70, 30);

        Tgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TglPropertyChange(evt);
            }
        });
        getContentPane().add(Tgl);
        Tgl.setBounds(330, 90, 150, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_18.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 490, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bersih (){
        TNama.setText(" ");
        TTtl.setText(" ");
        TAlamat.setText(" ");
        TPekerjaan.setText(" ");
        TId.setText(" ");
        THp.setText(" ");
        CBRegis.setSelectedIndex(0);        
        CBAgama.setSelectedIndex(0);
        CBPengenal.setSelectedIndex(0);
        buttonGroup1.setSelected(null, rootPaneCheckingEnabled);
    }
        
    public void getData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
                    
        try {
            Statement stat = (Statement) conek.GetConnection().createStatement();
            String sql = "Select * from tabkost1";
            ResultSet res = stat.executeQuery (sql);
            
        while(res.next()){
            Object[]obj = new Object[6];
            obj[0] = res.getString("Registrasi");
            obj[1] = res.getString("Nama");
            obj[2] = res.getString("Gender");
            obj[3] = res.getString("Agama");
            obj[4] = res.getString("Pekerjaan");
            obj[5] = res.getString("Telepon");
            
            model.addRow(obj);
                }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
            }
}
    
    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BDeleteActionPerformed

    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
        // TODO add your handling code here:
        new MenUtama().show();
        this.dispose();
    }//GEN-LAST:event_BHomeActionPerformed

    private void BSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSaveActionPerformed
        // TODO add your handling code here:
        String registrasi = (String) CBRegis.getSelectedItem();
        String nama = TNama.getText();
        String agama = (String) CBAgama.getSelectedItem();
        String pekerjaan = TPekerjaan.getText();
        String telepon = THp.getText();
        String gender = null;
        if (jRadioButton1.isSelected()){
            gender = "Laki-laki";
        }
        else
        if (jRadioButton2.isSelected()){
            gender = "Perempuan";
        }    
        
        try {
            Statement statement = (Statement)conek.GetConnection().createStatement();
            statement.executeUpdate("insert into tabkost1 VALUES('"+ registrasi +"','"+ nama +"','"+ agama +"','"+ gender +"','"+ pekerjaan +"','"+ telepon +"');");
            statement.close();
            JOptionPane.showMessageDialog(null,"Data berhasil disimpan!");
            bersih();
        }
        catch (Exception t){
            JOptionPane.showMessageDialog(null,"Data gagal disimpan!");
        }
        getData();
    }//GEN-LAST:event_BSaveActionPerformed

    private void BClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClearActionPerformed
        // TODO add your handling code here:
        String regis = (String) CBRegis.getSelectedItem();
        
        try {
            Statement statement=(Statement)conek.GetConnection().createStatement();
            statement.executeUpdate("DELETE from tabkost1 where Registrasi=('"+ regis +"');");
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus!");
            bersih();
            CBRegis.requestFocus();            
        }
        catch (Exception t){
            JOptionPane.showMessageDialog(null,"Data gagal dihapus!");
        }
        getData();
    }//GEN-LAST:event_BClearActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:           
    int i = tabel.getSelectedRow();
    if (i>=0){
    CBRegis.setSelectedItem(tabel.getValueAt(i, 0).toString());
    TNama.setText(tabel.getValueAt(i, 1).toString());
    CBAgama.setSelectedItem(tabel.getValueAt(i, 3));
    TPekerjaan.setText(tabel.getValueAt(i, 4).toString());
    THp.setText(tabel.getValueAt(i, 5).toString());
    }
    
       try{
            Statement statement=(Statement)conek.GetConnection().createStatement();
            statement.executeUpdate("Update tabkost1 set (Registrasi='"+ CBRegis.getSelectedItem() +"', Nama='"+ TNama.getText()+"', Gender='"+ buttonGroup1.getSelection() +"',Agama='"+ CBAgama.getSelectedItem() +"',Pekerjaan='"+ TPekerjaan.getText() + "',where telepon='"+ THp.getText()+"');");
            JOptionPane.showMessageDialog(null,"Data berhasil diedit!");
            bersih();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Edit Data sekarang!");
        }
       
            getData();
    }//GEN-LAST:event_BEditActionPerformed

    private void BReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReportActionPerformed
        // TODO add your handling code here:
          try {
            Desktop desktop = Desktop.getDesktop();
            URI url = new URI("http://localhost/phpmyadmin/sql.php?db=kost&table=tabkost1&printview=1&sql_query=SELECT+%2A+FROM+%60tabkost1%60&token=8a0b2233b39fc45137653af26d289cc7");
            if (Desktop.isDesktopSupported()) {
                try {
                    desktop.browse(url);
                } catch (IOException ex) {
                    Logger.getLogger(Penyewa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(Penyewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BReportActionPerformed

    private void CBPengenalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPengenalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPengenalActionPerformed

    private void TglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TglPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TglPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClear;
    private javax.swing.JButton BDelete;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHome;
    private javax.swing.JButton BReport;
    private javax.swing.JButton BSave;
    private javax.swing.JComboBox CBAgama;
    private javax.swing.JComboBox CBPengenal;
    private javax.swing.JComboBox CBRegis;
    private javax.swing.JTextField TAlamat;
    private javax.swing.JTextField THp;
    private javax.swing.JTextField TId;
    private javax.swing.JTextField TNama;
    private javax.swing.JTextField TPekerjaan;
    private javax.swing.JTextField TTtl;
    private com.toedter.calendar.JDateChooser Tgl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
